### ISSUE TITLE
Radio/checkboxes: where should we put the spans?

### ISSUE THREAD

**Issue by etiennesegonzac** [mozilla-b2g/Gaia-UI-Building-Blocks#1]
Looks like we're going to need to add a `span` in order to style everything.

Should it be:
- Around the input?
- Next to the input?

**Comment by pivanov** [comment]
The right way is to order elements like this: 
<:label>
    <:input />
    <:span><:/span>
<:/label>

because we use adjacent sibling combinator to show radio or checkboxes
