### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by fabi1cazenave** [mozilla-b2g/Gaia-UI-Building-Blocks#11]
I don’t understand the file structure. Having a README.md file in the root directory and in every child directory would help a lot.

**Comment by pivanov** [comment]
We have readme.md file in the root :)

**Comment by basiclines** [comment]
The file structure is always the same and is documented in readme file as @pivanov says.
We could think about which kind of information we can add to each BB folder as readme file.
