### ISSUE TITLE
HTML templates should pass the W3C validator

### ISSUE THREAD

**Issue by fabi1cazenave** [mozilla-b2g/Gaia-UI-Building-Blocks#12]
I’ve found (and corrected) a few HTML files where the opening `<html>` tag was missing. There are invalid attributes in other HTML files.

I understand running a local HTML5 validator isn’t trivial. At the very least, HTML files should be checked against an HTML5 validator after they’re published on gh-pages.

**Comment by caseyyee** [comment]
agreed, let's keep it validated.

thanks for fixing those up.
