### ISSUE TITLE
Come up with a file structure that simplifies using the BB in apps

### ISSUE THREAD

**Issue by jmcanterafonseca** [mozilla-b2g/Gaia-UI-Building-Blocks#17]
it is necessary to define a file structure that allows to use and replace easily the Gaia Building Blocks in apps. Should we have a folder per building block, a folder containing all building blocks? How this relates to the standard layout of files in Gaia?

**Comment by fabi1cazenave** [comment]
We talked about that with @caseyyee last week. The plan we agreed on was to have:
- one main _“testing”_ repository, containing markup that has been proposed;
- one main _“stable”_ directory, containing canonical markup that developers agree on.

… and in each main directory, I’d suggest to have a per-component file hierarchy (e.g. one directory per component or one filename per component). I don’t have any strong opinion about component subtrees; I just would like that the `url()` links in CSS resources remain unchanged.

Here’s one possible structure — suggestions highly welcome:

```
testing/
    headers/
        title/

stable/
    headers/
        […]
    tabs/
        style/
            topTabBG.png
            rightTabBG.png
            bottomTabBG.png
            leftTabBG.png
        tabsOnTop.html
        tabsOnTop.css
        tabsOnBottom.html
        tabsOnBottom.css
```

Another possible structure would be to have one directory per component but it could get a bit messy. Again, I don’t have any strong opinion besides the testing/stable thing.

@etiennesegonzac @caseyyee any opinion on this?

**Comment by fabi1cazenave** [comment]
Ooops, sorry. I meant:

```
testing/
    headers/
        title/

stable/
    headers/
        […]
    tabs/
        images/
            topTabBG.png
            rightTabBG.png
            bottomTabBG.png
            leftTabBG.png
        tabsOnTop.html
        tabsOnTop.css
        tabsOnBottom.html
        tabsOnBottom.css
```

or

```
testing/
    headers/
        title/

stable/
    headers/
        […]
    tabs/
        style/
            images/
                topTabBG.png
                rightTabBG.png
                bottomTabBG.png
                leftTabBG.png
            tabsOnBottom.css
            tabsOnTop.css
        tabsOnTop.html
        tabsOnBottom.html
```

or

```
testing/
    headers/
        title/

stable/
    headers/
        […]
    tabs/
        tabsOnTop/
            style/
                images/
                    topTabBG.png
                style.css
            index.html
        tabsOnBottom/
            style/
                images/
                    bottomTabBG.png
                style.css
            index.html
```

**Comment by jmcanterafonseca** [comment]
I prefer the one on which the CSS files are separated on the style folder. Then it would be easy to copy the whole folder to your app. However I don't understand quite well the difference between stable and test. If something it is only a test it can be on a branch ... 

I agree that having one directory per variant is too much. One directory per building block as per the taxonomy defined with UX sounds good
