### ISSUE TITLE
Markup for lists 

### ISSUE THREAD

**Issue by jmcanterafonseca** [mozilla-b2g/Gaia-UI-Building-Blocks#18]
This issue is for starting a discussion on the markup to be used for Lists. Lists are an important building block for B2G UI as they will be used in many different apps such as Contacts, Call Log, SMS, and more. 

Here are some proposed principles: anything with a role="list"  that is a descendent of  `<body role="application">` will be considered as a list in terms of styling. 

`<body role="application">`

 `<ul role="list">`
     `<li role="listitem"></li>`
 `</ul>`

I know it is a bit redundant as ul, ols and li has this intrinsically this role but it allows to avoid using arbitrary class names in our markup. 

There are lists in which the user can make a selection (for instance to select a set of FB contacts to be synchronized). In that particular case the correct role to be used is 'listbox'. In that case the markup will include the <input type="checkbox" necessary.  

now the next discussion is what markup should be used for what it is inside a listitem. This can be tricky, because it depends on the different variants for lists (see visual designs). The first thing we need to support is a figure associated to the list item that should be floated to the right. This can be done by using the figure element

`<li role="listitem">`
   `<figure><img src=""></figure>`
`</li>`

We can have different icons within a list item

`<li role="listitem">`
  `<span class="icon left missed-call">Missed Call</span>`
`</li>`

We can have also time elements that denote when an specific event happened. For doing so the time element should be used. 

Now that we have defined the auxiliary items within a listitem We need to make a decision on how to define the markup for the text. 

One option is to use the `<dl><dt><dd>`  pattern. Being the dt the main content and the rest content that complements it

`<dl>`
  `<dt>Mark Alfenito</dt>`
 `<dd>Family</dd>`
`</dl>`

We can have also

`<dl>`
  `<dt>Mark alfenito</dt>`
  `<dd><time>4:00</time></dd>`
  `<dd>Vivo</dd>`
`</dl>`

Another example could be something like

`<dl>`
  `<dt>John Doe</dt>`
  `<dd><time>2:00 PM</dd>`
  `<dd>`
  `<hgroup>`
     `<h1>This is the subject of the message</h1>`
    `<h2>This is an extract of the message</h2>`
  `</hgroup>`
     `</dd>`
`</dl>`

**Comment by fabi1cazenave** [comment]
(side note: with Github you can use this syntax to highlight blocks of HTML markup)

``````
    ```html
    <dl>
        <dt> foo </dt>
        <dd> bar </dd>
    </dd>
    ```
``````

About these `role="list"`:

> I know it is a bit redundant as ul, ols and li has this intrinsically this role but it allows to avoid using arbitrary class names in our markup.

It’s very redundant, indeed. Why can’t we just use plain `ul`, `ol` and `li` selectors? Are there specific examples for that in Gaia already?

**Comment by jmcanterafonseca** [comment]
In the contacts application we are using `<ol class="blocklist">`. 

I agree that adding he role is very redundant. I think we can enable Gaia lists but only taking into account if the list is within a `<body role="application">` . If authors of other applications want to opt out or use a different kind of list they can always use their own class names. 

Concerning the rest of the proposal are you ok?

**Comment by fabi1cazenave** [comment]
Agreed, let’s not use any extra tag (even an aria role) if it’s not required at the moment.

Concerning the rest of the proposal I think I’d prefer to see some per-widget HTML markup than discussing on general rules. I’m currently dealing with a lot of lists in the Settings app, so I guess I could start proposing a few list widgets in a pull request.

**Comment by jmcanterafonseca** [comment]
Please take a look also at the Visuals of Comms. We will be working on the proposal and make also a pull request

thanks!
