### ISSUE TITLE
Why using body[role="application"] in almost all selectors

### ISSUE THREAD

**Issue by RudyLu** [mozilla-b2g/Gaia-UI-Building-Blocks#33]
May I know if there is any specific purpose we are using body[role="application"] in the CSS selectors of building blocks?

e.g. 

``` css
  body[role="application"] [role="dialog"] {
   ... 
  }
```

I think only "[role="dialog"]" is enough for what we want to achieve.

The actual case affected by this in Gaia is System app.
  apps/system/index.html
We may not want to add [role="application"] to its body.

Thanks.

**Comment by pivanov** [comment]
this is old thing ... soon we will remove this from all of the Building Blogs ... we just do the new things 1 by 1 ... :)

**Comment by RudyLu** [comment]
Good to know.
Thanks for the info.
