### ISSUE TITLE
Using text-indent -9999px to hide text can cause element not to be pre-rendered.

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-b2g/Gaia-UI-Building-Blocks#37]
When using a building block icon you will start getting async log warning about some element in your document that can no longer run async animations because its frame is larger then the viewport. This can cause slow animations when using drawer (and any other animation that effects the main role="region").

This probably need to be paired with a gecko bug?

**Comment by pivanov** [comment]
Yep I agree with this ... maybe it's a good idea to use something like this :
.classname {
    display: inline-block;
    overflow: hidden;
    text-indent: 100%;
    white-space: nowrap;
}
