### ISSUE TITLE
input areas' use of reset inputs resets entire form

### ISSUE THREAD

**Issue by asutherland** [mozilla-b2g/Gaia-UI-Building-Blocks#59]
The input area building blocks example shows an idiom of using multiple &lt;p&gt;&lt;input /&gt;&lt;button type="reset"&gt;&lt;/p&gt; blocks within a single "form" tag.  While the reset button is styled in such a way that implies it resets only the input box in question, it will in fact reset every input within the form.

Based on how "reset" works, it seems like the example should be updated to contain each input within its own form (although that seems semantically ugly), or a JS helper is required.

**Comment by basiclines** [comment]
A JS helper is required as the examples shown are for tiny forms configurations.
That JS helper should be provided by application authors, the BB does not provide any JS.

Thx!

**Comment by asutherland** [comment]
It seems like there should at least be a comment to that effect in the example's HTML since there does not seem to be any other documentation to that effect.

**Comment by basiclines** [comment]
Sure we should do a follow up for appending this information on to the BB.
We can change the description issue to fit this requirment.
Thank you for your feedback!
