### ISSUE TITLE
Project should start using git tags. 

### ISSUE THREAD

**Issue by precz** [mozilla-b2g/Gaia-UI-Building-Blocks#68]
It's hard to use this project as a external library - project folders structure changes without making a new tag in repository! Now our build is broken!

When master changes new release should be made (new tag).
- [Tagging](http://git-scm.com/book/en/Git-Basics-Tagging).
- [Versioning](http://semver.org/).
- Project could be also added to [Bower](http://bower.io/) repository.

**Comment by precz** [comment]
How it should be done: https://github.com/precz/Gaia-UI-Building-Blocks/releases/tag/0.1.0

**Comment by Padam87** [comment]
:+1:
