### ISSUE TITLE
make Building-Blocks bower installable

### ISSUE THREAD

**Issue by gasolin** [mozilla-b2g/Gaia-UI-Building-Blocks#76]
I tried to register buildingblocks to bower, so user can run `bower install buildingblocks` to get the UI blocks.
https://github.com/bower/bower

To auto update the Building-Blocks version, the git tag need to use the formalized format defined in http://semver.org/
such as `1.0.0` or `1.0.0-alpha.1` or `v1.0.0` (v will be ignored)

**Comment by Padam87** [comment]
:+1:
